from PyQt5.QtCore import QRect

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 800
VIEWPORT_WIDTH = 600
VIEWPORT_HEIGHT = 600
VIEWPORT_X = 0
VIEWPORT_Y = 0
POINT_SIZE = 2

GENERAL_MARGIN = 10

TOOLS_FRAME_SIZE = (200, 580)
TOOLS_FRAME_GEOMETRY = (GENERAL_MARGIN, GENERAL_MARGIN, TOOLS_FRAME_SIZE[0], TOOLS_FRAME_SIZE[1])

VIEW_FRAME_SIZE = (600, 600)
VIEW_FRAME_GEOMETRY = (TOOLS_FRAME_SIZE[0] + 2*GENERAL_MARGIN, GENERAL_MARGIN, VIEW_FRAME_SIZE[0], VIEW_FRAME_SIZE[1])
VIEWPORT_GEOMETRY = QRect(0, 0, VIEW_FRAME_GEOMETRY[2], VIEW_FRAME_GEOMETRY[3])