# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPointDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class AddPointDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(279, 134)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageLabel = QtWidgets.QLabel(Dialog)
        self.messageLabel.setObjectName("messageLabel")
        self.verticalLayout.addWidget(self.messageLabel)
        self.addPointHorizontalLayout = QtWidgets.QHBoxLayout()
        self.addPointHorizontalLayout.setContentsMargins(-1, 0, 0, 35)
        self.addPointHorizontalLayout.setObjectName("addPointHorizontalLayout")
        self.xLabel = QtWidgets.QLabel(Dialog)
        self.xLabel.setObjectName("xLabel")
        self.addPointHorizontalLayout.addWidget(self.xLabel)
        self.xSpinBox = QtWidgets.QSpinBox(Dialog)
        self.xSpinBox.setObjectName("xSpinBox")
        self.addPointHorizontalLayout.addWidget(self.xSpinBox)
        self.yLabel = QtWidgets.QLabel(Dialog)
        self.yLabel.setObjectName("yLabel")
        self.addPointHorizontalLayout.addWidget(self.yLabel)
        self.ySpinBox = QtWidgets.QSpinBox(Dialog)
        self.ySpinBox.setObjectName("ySpinBox")
        self.addPointHorizontalLayout.addWidget(self.ySpinBox)
        self.addPointHorizontalLayout.setStretch(1, 100)
        self.addPointHorizontalLayout.setStretch(3, 100)
        self.verticalLayout.addLayout(self.addPointHorizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Point"))
        self.messageLabel.setText(_translate("Dialog", "Add the coordinates (x, y) of the point:"))
        self.xLabel.setText(_translate("Dialog", "x"))
        self.yLabel.setText(_translate("Dialog", "y"))