# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addWireframeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageLabel = QtWidgets.QLabel(Dialog)
        self.messageLabel.setObjectName("messageLabel")
        self.verticalLayout.addWidget(self.messageLabel)
        self.addPointHorizontalLayout = QtWidgets.QHBoxLayout()
        self.addPointHorizontalLayout.setObjectName("addPointHorizontalLayout")
        self.xLabel = QtWidgets.QLabel(Dialog)
        self.xLabel.setObjectName("xLabel")
        self.addPointHorizontalLayout.addWidget(self.xLabel)
        self.xSpinBox = QtWidgets.QSpinBox(Dialog)
        self.xSpinBox.setObjectName("xSpinBox")
        self.addPointHorizontalLayout.addWidget(self.xSpinBox)
        self.yLabel = QtWidgets.QLabel(Dialog)
        self.yLabel.setObjectName("yLabel")
        self.addPointHorizontalLayout.addWidget(self.yLabel)
        self.ySpinBox = QtWidgets.QSpinBox(Dialog)
        self.ySpinBox.setObjectName("ySpinBox")
        self.addPointHorizontalLayout.addWidget(self.ySpinBox)
        self.addButton = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.addButton.setIcon(icon)
        self.addButton.setObjectName("addButton")
        self.addPointHorizontalLayout.addWidget(self.addButton)
        self.addPointHorizontalLayout.setStretch(1, 100)
        self.addPointHorizontalLayout.setStretch(3, 100)
        self.verticalLayout.addLayout(self.addPointHorizontalLayout)
        self.itemsListWidget = QtWidgets.QListWidget(Dialog)
        self.itemsListWidget.setObjectName("itemsListWidget")
        self.verticalLayout.addWidget(self.itemsListWidget)
        self.removeButton = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.removeButton.setIcon(icon)
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout.addWidget(self.removeButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Wireframe"))
        self.messageLabel.setText(_translate("Dialog", "Add the points of the polygon:"))
        self.xLabel.setText(_translate("Dialog", "x"))
        self.yLabel.setText(_translate("Dialog", "y"))
        self.addButton.setText(_translate("Dialog", "Add item"))
        self.removeButton.setText(_translate("Dialog", "Remove item"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
