# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addLineDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from utils.constant import DEFAULT_SHAPE_COLOR


class AddLineDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(450, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(450, 300))
        Dialog.setMaximumSize(QtCore.QSize(450, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.messageLabel.setFont(font)
        self.messageLabel.setObjectName("messageLabel")
        self.verticalLayout.addWidget(self.messageLabel)
        self.infoHorizontalLayout = QtWidgets.QHBoxLayout()
        self.infoHorizontalLayout.setContentsMargins(-1, 11, -1, -1)
        self.infoHorizontalLayout.setObjectName("infoHorizontalLayout")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.infoHorizontalLayout.addWidget(self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.infoHorizontalLayout.addWidget(self.nameLineEdit)
        self.colorLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.colorLabel.setFont(font)
        self.colorLabel.setObjectName("colorLabel")
        self.infoHorizontalLayout.addWidget(self.colorLabel)
        self.colorButton = QtWidgets.QPushButton(Dialog)

        #TODO: O código gerado pela interface não usa a constante, caso atualize, use a constante depois
        self.colorButton.setStyleSheet("background-color: " + DEFAULT_SHAPE_COLOR.name() + ";")
        
        self.colorButton.setText("")
        self.colorButton.setObjectName("colorButton")
        self.infoHorizontalLayout.addWidget(self.colorButton)
        self.verticalLayout.addLayout(self.infoHorizontalLayout)
        self.addPoinstLineGridLayout = QtWidgets.QGridLayout()
        self.addPoinstLineGridLayout.setContentsMargins(-1, 6, -1, -1)
        self.addPoinstLineGridLayout.setObjectName("addPoinstLineGridLayout")
        self.x1Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.x1Label.setFont(font)
        self.x1Label.setObjectName("x1Label")
        self.addPoinstLineGridLayout.addWidget(self.x1Label, 0, 0, 1, 1)
        self.x1SpinBox = QtWidgets.QSpinBox(Dialog)
        self.x1SpinBox.setMinimum(-1000)
        self.x1SpinBox.setMaximum(1000)
        self.x1SpinBox.setObjectName("x1SpinBox")
        self.addPoinstLineGridLayout.addWidget(self.x1SpinBox, 0, 1, 1, 1)
        self.y1Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.y1Label.setFont(font)
        self.y1Label.setObjectName("y1Label")
        self.addPoinstLineGridLayout.addWidget(self.y1Label, 0, 2, 1, 1)
        self.y1SpinBox = QtWidgets.QSpinBox(Dialog)
        self.y1SpinBox.setMinimum(-1000)
        self.y1SpinBox.setMaximum(1000)
        self.y1SpinBox.setObjectName("y1SpinBox")
        self.addPoinstLineGridLayout.addWidget(self.y1SpinBox, 0, 3, 1, 1)
        self.x2Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.x2Label.setFont(font)
        self.x2Label.setObjectName("x2Label")
        self.addPoinstLineGridLayout.addWidget(self.x2Label, 1, 0, 1, 1)
        self.x2SpinBox = QtWidgets.QSpinBox(Dialog)
        self.x2SpinBox.setMinimum(-1000)
        self.x2SpinBox.setMaximum(1000)
        self.x2SpinBox.setObjectName("x2SpinBox")
        self.addPoinstLineGridLayout.addWidget(self.x2SpinBox, 1, 1, 1, 1)
        self.y2Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.y2Label.setFont(font)
        self.y2Label.setObjectName("y2Label")
        self.addPoinstLineGridLayout.addWidget(self.y2Label, 1, 2, 1, 1)
        self.y2SpinBox = QtWidgets.QSpinBox(Dialog)
        self.y2SpinBox.setMinimum(-1000)
        self.y2SpinBox.setMaximum(1000)
        self.y2SpinBox.setObjectName("y2SpinBox")
        self.addPoinstLineGridLayout.addWidget(self.y2SpinBox, 1, 3, 1, 1)
        self.addPoinstLineGridLayout.setColumnMinimumWidth(1, 100)
        self.addPoinstLineGridLayout.setColumnMinimumWidth(3, 100)
        self.addPoinstLineGridLayout.setColumnStretch(1, 100)
        self.addPoinstLineGridLayout.setColumnStretch(3, 100)
        self.verticalLayout.addLayout(self.addPoinstLineGridLayout)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(3, 100)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Line"))
        self.messageLabel.setText(_translate("Dialog", "Add the initial (x1, y1) and final (x2, y2) coordinates of the line:"))
        self.nameLabel.setText(_translate("Dialog", "Name"))
        self.colorLabel.setText(_translate("Dialog", "Color"))
        self.x1Label.setText(_translate("Dialog", "x1"))
        self.y1Label.setText(_translate("Dialog", "y1"))
        self.x2Label.setText(_translate("Dialog", "x2"))
        self.y2Label.setText(_translate("Dialog", "y2"))


    def get_name_value(self):
        return self.nameLineEdit.text()
    

    def get_color_value(self):
        return self.colorButton
    

    def get_x1_value(self):
        return self.x1SpinBox.value()


    def get_y1_value(self):
        return self.y1SpinBox.value()


    def get_x2_value(self):
        return self.x2SpinBox.value()


    def get_y2_value(self):
        return self.y2SpinBox.value()
