# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addLineDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class AddLineDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(364, 199)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message1Label = QtWidgets.QLabel(Dialog)
        self.message1Label.setObjectName("message1Label")
        self.verticalLayout.addWidget(self.message1Label)
        self.message2Label = QtWidgets.QLabel(Dialog)
        self.message2Label.setObjectName("message2Label")
        self.verticalLayout.addWidget(self.message2Label)
        self.addPoinstLineGridLayout = QtWidgets.QGridLayout()
        self.addPoinstLineGridLayout.setObjectName("addPoinstLineGridLayout")
        self.x1Label = QtWidgets.QLabel(Dialog)
        self.x1Label.setObjectName("x1Label")
        self.addPoinstLineGridLayout.addWidget(self.x1Label, 0, 0, 1, 1)
        self.x1SpinBox = QtWidgets.QSpinBox(Dialog)
        self.x1SpinBox.setObjectName("x1SpinBox")
        self.addPoinstLineGridLayout.addWidget(self.x1SpinBox, 0, 1, 1, 1)
        self.y1Label = QtWidgets.QLabel(Dialog)
        self.y1Label.setObjectName("y1Label")
        self.addPoinstLineGridLayout.addWidget(self.y1Label, 0, 2, 1, 1)
        self.y1SpinBox = QtWidgets.QSpinBox(Dialog)
        self.y1SpinBox.setObjectName("y1SpinBox")
        self.addPoinstLineGridLayout.addWidget(self.y1SpinBox, 0, 3, 1, 1)
        self.x2Label = QtWidgets.QLabel(Dialog)
        self.x2Label.setObjectName("x2Label")
        self.addPoinstLineGridLayout.addWidget(self.x2Label, 1, 0, 1, 1)
        self.x2SpinBox = QtWidgets.QSpinBox(Dialog)
        self.x2SpinBox.setObjectName("x2SpinBox")
        self.addPoinstLineGridLayout.addWidget(self.x2SpinBox, 1, 1, 1, 1)
        self.y2Label = QtWidgets.QLabel(Dialog)
        self.y2Label.setObjectName("y2Label")
        self.addPoinstLineGridLayout.addWidget(self.y2Label, 1, 2, 1, 1)
        self.y2SpinBox = QtWidgets.QSpinBox(Dialog)
        self.y2SpinBox.setObjectName("y2SpinBox")
        self.addPoinstLineGridLayout.addWidget(self.y2SpinBox, 1, 3, 1, 1)
        self.addPoinstLineGridLayout.setColumnMinimumWidth(1, 100)
        self.addPoinstLineGridLayout.setColumnMinimumWidth(3, 100)
        self.addPoinstLineGridLayout.setColumnStretch(1, 100)
        self.addPoinstLineGridLayout.setColumnStretch(3, 100)
        self.verticalLayout.addLayout(self.addPoinstLineGridLayout)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(3, 100)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Line"))
        self.message1Label.setText(_translate("Dialog", "Add the initial (x1, y1) and final (x2, y2) coordinates"))
        self.message2Label.setText(_translate("Dialog", "of the line"))
        self.x1Label.setText(_translate("Dialog", "x1"))
        self.y1Label.setText(_translate("Dialog", "y1"))
        self.x2Label.setText(_translate("Dialog", "x2"))
        self.y2Label.setText(_translate("Dialog", "y2"))
