# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addRectangleDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class AddRectangleDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(333, 198)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message1Label = QtWidgets.QLabel(Dialog)
        self.message1Label.setObjectName("message1Label")
        self.verticalLayout.addWidget(self.message1Label)
        self.message2Label = QtWidgets.QLabel(Dialog)
        self.message2Label.setObjectName("message2Label")
        self.verticalLayout.addWidget(self.message2Label)
        self.rectangleConfigurationGridLayout = QtWidgets.QGridLayout()
        self.rectangleConfigurationGridLayout.setContentsMargins(-1, 0, -1, -1)
        self.rectangleConfigurationGridLayout.setObjectName("rectangleConfigurationGridLayout")
        self.xLabel = QtWidgets.QLabel(Dialog)
        self.xLabel.setObjectName("xLabel")
        self.rectangleConfigurationGridLayout.addWidget(self.xLabel, 0, 0, 1, 1)
        self.xSpinBox = QtWidgets.QSpinBox(Dialog)
        self.xSpinBox.setObjectName("xSpinBox")
        self.rectangleConfigurationGridLayout.addWidget(self.xSpinBox, 0, 1, 1, 1)
        self.yLabel = QtWidgets.QLabel(Dialog)
        self.yLabel.setObjectName("yLabel")
        self.rectangleConfigurationGridLayout.addWidget(self.yLabel, 0, 2, 1, 1)
        self.ySpinBox = QtWidgets.QSpinBox(Dialog)
        self.ySpinBox.setObjectName("ySpinBox")
        self.rectangleConfigurationGridLayout.addWidget(self.ySpinBox, 0, 3, 1, 1)
        self.widhtLabel = QtWidgets.QLabel(Dialog)
        self.widhtLabel.setObjectName("widhtLabel")
        self.rectangleConfigurationGridLayout.addWidget(self.widhtLabel, 1, 0, 1, 1)
        self.widhtSpinBox = QtWidgets.QSpinBox(Dialog)
        self.widhtSpinBox.setObjectName("widhtSpinBox")
        self.rectangleConfigurationGridLayout.addWidget(self.widhtSpinBox, 1, 1, 1, 1)
        self.heightLabel = QtWidgets.QLabel(Dialog)
        self.heightLabel.setObjectName("heightLabel")
        self.rectangleConfigurationGridLayout.addWidget(self.heightLabel, 1, 2, 1, 1)
        self.heightSpinBox = QtWidgets.QSpinBox(Dialog)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self.rectangleConfigurationGridLayout.addWidget(self.heightSpinBox, 1, 3, 1, 1)
        self.rectangleConfigurationGridLayout.setColumnMinimumWidth(1, 100)
        self.rectangleConfigurationGridLayout.setColumnMinimumWidth(3, 100)
        self.rectangleConfigurationGridLayout.setColumnStretch(1, 100)
        self.rectangleConfigurationGridLayout.setColumnStretch(3, 100)
        self.verticalLayout.addLayout(self.rectangleConfigurationGridLayout)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(3, 100)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Rectangle"))
        self.message1Label.setText(_translate("Dialog", "Add the lower left coordinate (x, y) and width,"))
        self.message2Label.setText(_translate("Dialog", "height of the rectangle:"))
        self.xLabel.setText(_translate("Dialog", "x"))
        self.yLabel.setText(_translate("Dialog", "y"))
        self.widhtLabel.setText(_translate("Dialog", "widht"))
        self.heightLabel.setText(_translate("Dialog", "height"))
