# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addWireframeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QListWidgetItem
from PyQt5.QtCore import Qt


class AddWireframeDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageLabel = QtWidgets.QLabel(Dialog)
        self.messageLabel.setObjectName("messageLabel")
        self.verticalLayout.addWidget(self.messageLabel)
        self.addPointHorizontalLayout = QtWidgets.QHBoxLayout()
        self.addPointHorizontalLayout.setObjectName("addPointHorizontalLayout")
        self.xLabel = QtWidgets.QLabel(Dialog)
        self.xLabel.setObjectName("xLabel")
        self.addPointHorizontalLayout.addWidget(self.xLabel)
        self.xSpinBox = QtWidgets.QSpinBox(Dialog)
        self.xSpinBox.setMaximum(99999)
        self.xSpinBox.setObjectName("xSpinBox")
        self.addPointHorizontalLayout.addWidget(self.xSpinBox)
        self.yLabel = QtWidgets.QLabel(Dialog)
        self.yLabel.setObjectName("yLabel")
        self.addPointHorizontalLayout.addWidget(self.yLabel)
        self.ySpinBox = QtWidgets.QSpinBox(Dialog)
        self.ySpinBox.setMaximum(99999)
        self.ySpinBox.setObjectName("ySpinBox")
        self.addPointHorizontalLayout.addWidget(self.ySpinBox)
        self.addButton = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.addButton.setIcon(icon)
        self.addButton.setDefault(True)
        self.addButton.setObjectName("addButton")
        self.addPointHorizontalLayout.addWidget(self.addButton)
        self.addPointHorizontalLayout.setStretch(1, 100)
        self.addPointHorizontalLayout.setStretch(3, 100)
        self.verticalLayout.addLayout(self.addPointHorizontalLayout)
        self.itemsListWidgetGridLayout = QtWidgets.QGridLayout()
        self.itemsListWidgetGridLayout.setObjectName("itemsListWidgetGridLayout")
        self.yListLabel = QtWidgets.QLabel(Dialog)
        self.yListLabel.setObjectName("yListLabel")
        self.itemsListWidgetGridLayout.addWidget(self.yListLabel, 0, 1, 1, 1)
        self.xListLabel = QtWidgets.QLabel(Dialog)
        self.xListLabel.setObjectName("xListLabel")
        self.itemsListWidgetGridLayout.addWidget(self.xListLabel, 0, 0, 1, 1)
        self.itemsXListWidget = QtWidgets.QListWidget(Dialog)
        self.itemsXListWidget.setObjectName("itemsXListWidget")
        self.itemsListWidgetGridLayout.addWidget(self.itemsXListWidget, 1, 0, 1, 1)
        self.itemsYListWidget = QtWidgets.QListWidget(Dialog)
        self.itemsYListWidget.setObjectName("itemsYListWidget")
        self.itemsListWidgetGridLayout.addWidget(self.itemsYListWidget, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.itemsListWidgetGridLayout)
        self.removeButton = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.removeButton.setIcon(icon)
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout.addWidget(self.removeButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Wireframe"))
        self.messageLabel.setText(_translate("Dialog", "Add the points of the polygon:"))
        self.xLabel.setText(_translate("Dialog", "x"))
        self.yLabel.setText(_translate("Dialog", "y"))
        self.addButton.setText(_translate("Dialog", "Add item"))
        self.yListLabel.setText(_translate("Dialog", "y"))
        self.xListLabel.setText(_translate("Dialog", "x"))
        self.removeButton.setText(_translate("Dialog", "Remove item"))


    def get_points_value(self):
        points = []

        for index in range(self.itemsXListWidget.count()):
            item = self.itemsXListWidget.item(index)
            x_value = int(item.text())
            
            y_item = self.itemsYListWidget.item(index)
            y_value = int(y_item.text())

            points.append((x_value, y_value))

        return points
    

    def add_x_item(self, x):
        item = QListWidgetItem(str(x))
        
        selected_item = self.itemsXListWidget.currentItem()
        
        if selected_item:
            index = self.itemsXListWidget.row(selected_item)
            self.itemsXListWidget.insertItem(index + 1, item)
        else:
            self.itemsXListWidget.addItem(item)

        row = self.itemsXListWidget.row(item)
        self.itemsXListWidget.setCurrentRow(row)


    def add_y_item(self, y):
        item = QListWidgetItem(str(y))
        
        selected_item = self.itemsYListWidget.currentItem()
        
        if selected_item:
            index = self.itemsYListWidget.row(selected_item)
            self.itemsYListWidget.insertItem(index + 1, item)
        else:
            self.itemsYListWidget.addItem(item)
        
        row = self.itemsYListWidget.row(item)
        self.itemsYListWidget.setCurrentRow(row)


    def add_item(self):
        x = self.xSpinBox.value()
        y = self.ySpinBox.value()

        self.add_x_item(x)
        self.add_y_item(y)

        self.xSpinBox.setValue(self.xSpinBox.minimum())
        self.ySpinBox.setValue(self.ySpinBox.minimum())

        self.xSpinBox.setFocus()

    def remove_item(self):
        x_selected_items = self.itemsXListWidget.selectedItems()
        y_selected_items = self.itemsYListWidget.selectedItems()

        for x_item in x_selected_items:
            row = self.itemsXListWidget.row(x_item)
            self.itemsXListWidget.takeItem(row)

        for y_item in y_selected_items:
            row = self.itemsYListWidget.row(y_item)
            self.itemsYListWidget.takeItem(row)
